apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0004
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /Netreg
    server: 128.49.90.63
  persistentVolumeReclaimPolicy: Retain
